# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Статьи'},
        ),
    ]
